### ISSUE TITLE
Error: Stream yields empty buffer

### ISSUE THREAD

**Issue by KushalPanchal28** [AnyChart/AnyChart-NodeJS#20]
Anychart is able to create the chart. but it is unable to save it to jpg file.
Gives out this error
Error: Stream yields empty buffer
    at Socket.<anonymous> (/usr/local/lib/node_modules/anychart-nodejs/node_modules/gm/lib/command.js:57:17)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

Details:
Server Provider: Digital Ocean
Ubuntu: 16.0.4
node: 12.4.0
anychart: 8.3.0
anychart-nodejs: 1.3.8
ImageMagick : 7.0.8-11
librsvg2-dev: 2.40.13-3
librsvg2-bin: 2.40.13-3

**Comment by Shestac92** [comment]
@KushalPanchal28 
The similar problem was solved by using other module versions. For details, please, check [this issue comment](https://github.com/AnyChart/AnyChart-NodeJS/issues/17#issuecomment-461828627).
